### ISSUE TITLE
Create custom signin page for Next Auth Signin

### ISSUE THREAD

**Issue by ChiragAgg5k** [ChiragAgg5k/bug-squash#22]
**Is your feature request related to a problem? Please describe.**
Currently the page redirects to the default signin page provided by Next Auth.

**Describe the solution you'd like**
A custom signin page that matches overall theme of the project.

The page should go here - `app/auth/signin/page.tsx`. It should have same functionality as the default sigin page, with all the required buttons. Make it as creative as you want

**Describe alternatives you've considered**
It's not necessary for you to code the logic for the frontend to connect with backend. Main thing i am looking for is design.

**Screenshots**

Current Signin Page :

<img width="577" alt="Screenshot 2023-09-29 at 4 01 29 PM" src="https://github.com/ChiragAgg5k/bug-squash/assets/110609663/72abab58-b43f-4838-af4c-4adef52c9414">

**Comment by princyballabh** [comment]
Hello!
I am a beginner and have knowledge about HTML and CSS. I would like to design the signin page. Can you please tell a bit about how to get started with this.

**Comment by ChiragAgg5k** [comment]
@princyballabh hey there. First of all the project is made using nextjs, so you would require knowledge of React as well to create the page.

Still if you would just like to design the page, u can do so and push it and i will transcribe it in react myself.

About the design itself, just try to match theme of the overall application (checkout the demo account) and rest is upto your creativity

**Comment by princyballabh** [comment]
Hey, I checked the live demo but error 404 is occurring. Also the thumbnail and logo png is unavailable. Can you please look into this.

**Comment by ChiragAgg5k** [comment]
https://www.bug-squash.co/

The site is giving 404 error? It is working fine for me. Can you try using a VPN? some ISP may have blocked the domain since its pending verification by porkbun

**Comment by princyballabh** [comment]
I am working on the design. Will create a PR by today.
